name = "email-worker"
main = "email-worker.js"
compatibility_date = "2024-09-15"
compatibility_flags = ["nodejs_compat"]
account_id = "84f0f32886f1d6196380fe6cbe9656a8"
workers_dev = true

# Email routing trigger with AI enhancement
# Email routing is configured in Cloudflare Dashboard
# This worker handles email for multiple domains with AI-powered classification
# Supports: nevershitty.com, chitty.cc, chicagofurnishedcondos.com, and more
# Features: AI classification, sentiment analysis, urgency detection, smart routing

# Workers AI binding for email processing
[ai]
binding = "AI"

# KV namespaces for analytics and rate limiting
[[kv_namespaces]]
binding = "EMAIL_ANALYTICS"
id = "email_analytics_kv"
preview_id = "email_analytics_preview"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "rate_limits_kv"
preview_id = "rate_limits_preview"

# Optional: Financial emails tracking
[[kv_namespaces]]
binding = "FINANCIAL_EMAILS"
id = "financial_emails_kv"
preview_id = "financial_emails_preview"

# Environment variables
[vars]
DOMAIN = "nevershitty.com"
ENVIRONMENT = "production"
DEFAULT_FORWARD = "no-reply@itcan.llc"
EVIDENCE_ROUTER_URL = "https://router.chitty.cc/litigation/evidence/intake"
FINANCE_ROUTER_URL = "https://router.chitty.cc/finance/intake"
COMPLIANCE_ROUTER_URL = "https://router.chitty.cc/compliance/intake"
TRACKING_ROUTER_URL = "https://router.chitty.cc/tracking/intake"
FEEDBACK_ENABLED = "true"

# Secrets (add via wrangler)
# wrangler secret put CHITTY_API_KEY
# wrangler secret put WEBHOOK_URL
# Cron triggers for weekly impact reports
[[triggers.crons]]
cron = "0 9 * * MON"  # Weekly impact report every Monday at 9am
