name = "email-worker-ai"
main = "email-worker-ai.js"
compatibility_date = "2024-09-15"
compatibility_flags = ["nodejs_compat"]
account_id = "84f0f32886f1d6196380fe6cbe9656a8"
workers_dev = true

# AI binding for Cloudflare Workers AI
[ai]
binding = "AI"

# KV namespaces for enhanced functionality
[[kv_namespaces]]
binding = "EMAIL_ANALYTICS"
id = "email_analytics_kv"
preview_id = "email_analytics_preview"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "rate_limits_kv"
preview_id = "rate_limits_preview"

[[kv_namespaces]]
binding = "SUPPORT_TICKETS"
id = "support_tickets_kv"
preview_id = "support_tickets_preview"

[[kv_namespaces]]
binding = "TASKS"
id = "tasks_kv"
preview_id = "tasks_preview"

[[kv_namespaces]]
binding = "FINANCIAL_EMAILS"
id = "financial_kv"
preview_id = "financial_preview"

[[kv_namespaces]]
binding = "LEGAL_EMAILS"
id = "legal_kv"
preview_id = "legal_preview"

[[kv_namespaces]]
binding = "CALENDAR_EVENTS"
id = "calendar_kv"
preview_id = "calendar_preview"

[[kv_namespaces]]
binding = "EMAIL_ARCHIVE"
id = "archive_kv"
preview_id = "archive_preview"

[[kv_namespaces]]
binding = "AUTO_RESPONSES"
id = "auto_responses_kv"
preview_id = "auto_responses_preview"

[[kv_namespaces]]
binding = "AI_LEARNING"
id = "ai_learning_kv"
preview_id = "ai_learning_preview"

# Environment variables
[vars]
DOMAIN = "nevershitty.com"
ENVIRONMENT = "production"
DEFAULT_FORWARD = "no-reply@itcan.llc"

# Secrets (add via wrangler)
# wrangler secret put CHITTY_API_KEY
# wrangler secret put WEBHOOK_URL